name: facilities-change-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - fiona=1
  - shapely=2
  - pyproj=3
  - requests=2
  - psycopg2=2
  - tqdm=4
  - typer=0
  - python-calamine=0
  - pandas=2
  - geopandas=0
  - lxml=5
